Repository netlify/functions, pull requests merged in 2021-11, with the labels that each got.

#214 chore: add automated pre-release process
  .github/workflows/pre-release.yml
  CONTRIBUTING.md
Labels: type: chore

#217 feat: add API authentication support
  package-lock.json
  src/function/handler.ts
  src/function/index.ts
  src/lib/builder.ts
  src/lib/secrets.ts
  src/lib/secrets_helper.ts
Labels: type: feature, automerge

#213 feat: use builder plugin metadata to set ODB TTL
  src/function/handler.ts
  src/function/response.ts
  src/lib/builder.ts
  src/lib/secrets.ts
  test/builder.js
Labels: type: feature
