Repository netlify/functions, pull requests merged in 2022-01, with the labels that each got.

#305 chore: fix Husky
  package-lock.json
  package.json
Labels: type: chore

#306 fix: husky binary not found
  package-lock.json
  package.json
Labels: type: bug, automerge

#226 feat: add schedule helper
  README.md
  src/lib/schedule.ts
  src/main.ts
Labels: type: feature

#313 refactor(authlify): expose `authlifyToken` directly
  src/lib/secrets_helper.ts
Labels: type: chore, automerge

#222 fix(handler type): make callback parameter optional
  src/function/handler.ts
  src/lib/builder.ts
Labels: type: bug, automerge
