Repository netlify/functions, pull requests merged in 2022-10, with the labels that each got.

#363 chore: update eslint rules
  .eslintrc.js
  package-lock.json
  package.json
  src/function/handler.ts
  src/function/index.ts
  src/lib/builder.ts
  src/lib/graph.ts
  src/lib/graph_token.ts
  src/lib/schedule.ts
  src/lib/secrets_helper.ts
  src/main.ts
  test/unit/builder.js
Labels: type: chore

#364 feat: add new BackgroundHandler type
  .eslintrc.js
  package-lock.json
  package.json
  src/function/handler.ts
  src/function/index.ts
  test/types/BackgroundHandler.test-d.ts
  test/types/Handler.test-d.ts
Labels: type: bug, type: feature

#350 chore: update CODEOWNERS file
  .github/CODEOWNERS
Labels: type: chore, automerge
